version: '3'
services:
  postgres:
    container_name: react-avancado-postgres
    image: postgres:14
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./.docker_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

